name: Build Windows x64 ZIP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Cache
      uses: actions/cache@v4
      with:
        path: Build/WinMergeDownloadDeps
        key: WinMergeDownloadDeps

    - name: Build x64 zip
      shell: cmd
      run: |
        call .\DownloadDeps.cmd
        Build\msys2\usr\bin\re2c.exe Src\FilterEngine\FilterLexer.re -o Src\FilterEngine\FilterLexer.cpp
        Build\msys2\usr\bin\lemon.exe Src\FilterEngine\FilterParser.y -TBuild\msys2\usr\share\lemon\lempar.c
        call .\BuildManual.cmd
        call .\BuildBin.vs2022.cmd x64
        call .\Testing\GoogleTest\UnitTests\UnitTests.exe
        call .\BuildTranslations.cmd
        call .\BuildArc.cmd x64 -ci

    - name: Upload zip
      uses: actions/upload-artifact@v4
      with:
        name: WinMerge-x64.zip
        path: Build/Releases/*-x64-exe.zip
