name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    
    runs-on: windows-2022

    steps:  
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: Build/WinMergeDownloadDeps
        key: ${{ runner.os }}-winmerge-download-deps-v2-${{ hashFiles('DownloadDeps.cmd') }}
        restore-keys: |
          ${{ runner.os }}-winmerge-download-deps-v2-

    - name: Build
      shell: cmd
      run: |
        call .\DownloadDeps.cmd
        if errorlevel 1 exit /b 1
        call .\BuildAll.vs2022.cmd x64 -ci
        if errorlevel 1 exit /b 1

    - name: Upload zip
      uses: actions/upload-artifact@v4
      with:
        name: WinMerge-x64.zip
        path: Build/Releases/*.zip

    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: WinMerge-x64-Setup-x64.exe
        path: Build/Releases/*.exe
