name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    
    runs-on: windows-2022

    steps:  
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: Build/WinMergeDownloadDeps
        key: ${{ runner.os }}-winmerge-download-deps-v3-${{ hashFiles('DownloadDeps.cmd') }}
        restore-keys: |
          ${{ runner.os }}-winmerge-download-deps-v3-

    - name: Build
      shell: cmd
      run: |
        call .\DownloadDeps.cmd
        if errorlevel 1 exit /b 1
        call .\BuildBin.vs2022.cmd x64
        if errorlevel 1 exit /b 1
        if not exist ".\Testing\GoogleTest\UnitTests\UnitTests.exe" (
          echo UnitTests.exe was not produced by BuildBin.vs2022.cmd
          exit /b 1
        )
        pushd .\Testing\GoogleTest\UnitTests
        if errorlevel 1 exit /b 1
        call .\UnitTests.exe
        if errorlevel 1 exit /b 1
        popd
        call .\BuildTranslations.cmd
        if errorlevel 1 exit /b 1
        call .\BuildArc.cmd x64 -ci
        if errorlevel 1 exit /b 1

    - name: Upload zip
      uses: actions/upload-artifact@v4
      with:
        name: WinMerge-x64.zip
        path: Build/Releases/*.zip
